image:
  repository: pegasyseng/web3signer
  tag: develop
  pullPolicy: Always

replicaCount: 1

persistence:
  diskSize: "50Mi"

# Additional web3signer command line arguments
args: []

service:
  enabled: true
  type: ClusterIP
  # clusterIP: None
  port: 9000
  hostAllowList: "localhost, 127.0.0.1"
  metrics: false
  metricsPort: 9001
  metricsHostAllowList: "localhost, 127.0.0.1"

serviceMonitor:
  enabled: false
  additionalLabels: {}
  namespace: ""
  namespaceSelector: {}
  # Default: scrape .Release.Namespace only
  # To scrape all, use the following:
  # namespaceSelector:
  #   any: true
  scrapeInterval: 15s
  # honorLabels: true
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
