apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "web3signer.fullname" . }}
  labels:
    app: {{ template "web3signer.name" . }}
    chart: {{ template "web3signer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "web3signer.name" . }}
      release: {{ .Release.Name }}

  {{- with .Values.updateStrategy}}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end}}

  serviceName: {{ .Release.Name }}
  podManagementPolicy: {{.Values.podManagementPolicy |  default "Parallel" }}
  template:
    metadata:
      labels:
        app: {{ template "web3signer.name" . }}
        release: {{ .Release.Name }}
      annotations:
        configHash: {{ include (print $.Template.BasePath "/configmap.tpl") . | sha256sum  }}
    spec:
      {{- with .Values.securityContext}}
      securityContext:
        {{- toYaml . | nindent 10 }}
      {{- end}}

      containers:
      - name: web3signer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.command}}
        command:
          {{- toYaml . | nindent 10 }}
        {{- end}}
        args:
          - --http-listen-port={{ .Values.service.port }}
          - --http-listen-host=0.0.0.0
          - --http-host-allowlist={{ .Values.service.hostAllowList }}
          - --key-store-path=/data
          - --logging=ALL
          {{- if .Values.service.metrics }}
          - --metrics-enabled
          - --metrics-port={{ .Values.service.metricsPort }}
          - --metrics-host=0.0.0.0
          - --metrics-host-allowlist={{ .Values.service.metricsHostAllowList }}
          {{- end }}
        {{- with .Values.args }}
          {{- toYaml . | nindent 10 }}
        {{- end}}
        {{- with .Values.env}}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end}}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
        - containerPort: {{ .Values.service.metricsPort }}
          name: metrics
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end}}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end}}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: {{ template "web3signer.fullname" . }}
          mountPath: /data

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 11 }}

  volumeClaimTemplates:
  - metadata:
      name: {{ template "web3signer.fullname" . }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.persistence.storageClassName | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.diskSize | quote }}
